model = "gpt-5.1-codex-max"
model_reasoning_effort = "high"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = true

[features]
web_search_request = true

[projects."/Users/colinzhao/src/personal/codex"]
trust_level = "trusted"

[projects."/Users/colinzhao/src/wags/wags"]
trust_level = "trusted"

[projects."/Users/colinzhao/dots/.config/nvim/.git/modules/lua"]
trust_level = "trusted"

[projects."/Users/colinzhao/dots/.config/nvim/lua/nvim-claude/lua/nvim-claude/agent_provider/providers/codex/codex"]
trust_level = "trusted"

[projects."/Users/colinzhao/tmp/zed"]
trust_level = "trusted"

[projects."/Users/colinzhao/dots/.config/nvim/.git/modules/lua/nvim-claude/modules/lua/nvim-claude/agent_provider/providers/codex"]
trust_level = "trusted"

[projects."/Users/colinzhao/tmp/codex"]
trust_level = "trusted"

[projects."/Users/colinzhao/School/2025-2026/cs188/Momentum-Agent"]
trust_level = "trusted"

# [mcp_servers.nvim-lsp]
# command = "/Users/colinzhao/.local/share/nvim/nvim-claude/mcp-env/bin/python"
# args = ["/Users/colinzhao/.config/nvim/lua/nvim-claude/mcp-server/nvim-lsp-server.py"]
[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[mcp_servers.nvim-lsp]
command = "/Users/colinzhao/.local/share/nvim/nvim-claude/mcp-env/bin/python"
args = ["/Users/colinzhao/.config/nvim/lua/nvim-claude/mcp-server/nvim-lsp-server.py"]
[otel]
environment = "dev"
log_user_prompt = true
exporter = { otlp-http = { endpoint = "http://127.0.0.1:4318/v1/logs", protocol = "json", headers = {} } }

